# -*- coding: utf-8 -*-
"""Banking_Project - EDA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zg4pNkYtlLzx-3n53ixlnrNIIRq89Qk
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv('/content/Banking.csv')
df.head(5)

df.shape

df.info()

# Generating Descriptive Statistics for the Dataframe
df.describe()

df['Estimated Income'].value_counts()

df['Estimated Income'].min()

bins = [0, 100000,300000, float('inf')]
labels = ['Low','Medium','High']

df['Income Band'] = pd.cut(df['Estimated Income'], bins=bins, labels=labels, right = False)

df['Income Band'].value_counts()

df['Income Band'].value_counts().plot(kind='bar')

# Examine the distribution of unique categories in categorical columns
categorical_cols = df[['BRId', 'GenderId', 'IAId', 'Amount of Credit Cards', 'Nationality', 'Occupation', 'Fee Structure', 'Loyalty Classification', 'Properties Owned', 'Risk Weighting', 'Income Band']]

for col in categorical_cols:
  print(f"Value Counts for '{col}':")
  display(df[col].value_counts())

"""Bivariate Analysis"""

for i, predictor in enumerate(df[['BRId', 'GenderId', 'IAId', 'Amount of Credit Cards', 'Nationality', 'Occupation', 'Fee Structure', 'Loyalty Classification', 'Properties Owned', 'Risk Weighting', 'Income Band']]):
  plt.figure(i)
  sns.countplot(data=df, x=predictor, hue='Nationality')

"""Univariate Analysis"""

for i, predictor in enumerate(df[['BRId', 'GenderId', 'IAId', 'Amount of Credit Cards', 'Nationality', 'Occupation', 'Fee Structure', 'Loyalty Classification', 'Properties Owned', 'Risk Weighting', 'Income Band']]):
  plt.figure(i)
  sns.countplot(data=df, x=predictor)

#Histplot of value counts for different Occupation

for col in categorical_cols:
  if col == 'Occupation':
    continue
  plt.figure(figsize=(8,4))
  sns.histplot(df[col])
  plt.title("Histogram of Occupation Count")
  plt.xlabel("Col")
  plt.ylabel("Count")
  plt.show()

"""## Numerical Analysis"""

numerical_cols = ['Estimated Income', 'Superannuation Savings','Credit Card Balance', 'Bank Loans', 'Bank Deposits', 'Checking Accounts', 'Saving Accounts', 'Foreign Currency Account', 'Business Lending']

#Univariate analysis
plt.figure(figsize=(15, 20))
for i, col in enumerate(numerical_cols):
    plt.subplot(4,3,i+1)
    sns.histplot(df[col],kde=True)
    plt.title(col)
plt.show()

"""## Heatmaps"""

numerical_cols = ['Estimated Income', 'Superannuation Savings','Credit Card Balance', 'Bank Loans', 'Bank Deposits', 'Checking Accounts', 'Saving Accounts', 'Foreign Currency Account', 'Business Lending']

correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(12,12))
sns.heatmap(correlation_matrix, annot=True, cmap='crest', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

"""## Insights of EDA

1. The Strongest positive correlation occur among "Bnk Deposits" with "Checking Accounts", "Savings Account" and "Foreign Currency Account" indicating that customers who maintain high balances in one account type often hold substntial amount/funds across other accounts as well.
"""
